id: I5105FA58
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T02:00:24+00:00'
last_modified: '2022-06-07T16:54:13.664304+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD19364
  title: བོད་རིག་པ་དུས་དེབ། ༼རྒྱ་ཡིག༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    07D6:
      image_group_id: I4PD4658
      title: ''
      total_pages: 252
      order: 1
      base_file: 07D6.txt
    1B95:
      image_group_id: I4PD4659
      title: ''
      total_pages: 218
      order: 2
      base_file: 1B95.txt
    EBB7:
      image_group_id: I4PD4660
      title: ''
      total_pages: 316
      order: 3
      base_file: EBB7.txt
    C5B5:
      image_group_id: I4PD4661
      title: ''
      total_pages: 316
      order: 4
      base_file: C5B5.txt
    722B:
      image_group_id: I4PD4662
      title: ''
      total_pages: 278
      order: 5
      base_file: 722B.txt
    4DDA:
      image_group_id: I4PD4663
      title: ''
      total_pages: 213
      order: 6
      base_file: 4DDA.txt
    B439:
      image_group_id: I4PD4664
      title: ''
      total_pages: 338
      order: 7
      base_file: B439.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
